//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIT14_ASSIGNMENT_PIZZA_ORDERING_SYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Order
    {
        public int CustomerID { get; set; }
        public int OrderID { get; set; }
        public string Pizza_Size { get; set; }
        public string Crust_Type { get; set; }
        public string Cheese_Type { get; set; }
        public string Dough_Type { get; set; }
        public string Pepperroni { get; set; }
        public string Green_Onions { get; set; }
        public string Red_Onions { get; set; }
        public string Ancovies { get; set; }
        public string Mushrooms { get; set; }
        public string Black_Olives { get; set; }
        public string Ham { get; set; }
        public string Pineapple { get; set; }
        public string Coca_Cola { get; set; }
        public string Pepsi { get; set; }
        public string Water { get; set; }
        public string Nacho_Bites { get; set; }
        public string Mozzarella_Sticks { get; set; }
        public string Username { get; set; }
    }
}
