//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIT14_ASSIGNMENT_PIZZA_ORDERING_SYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Customer_order = new HashSet<Customer_order>();
        }
    
        public int Customer_ID { get; set; }
        public string Collection_method { get; set; }
        public Nullable<decimal> Total_order_cost { get; set; }
        public string Full_name { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Address_Line_3 { get; set; }
        public string Post_code { get; set; }
        public string Email { get; set; }
        public Nullable<int> Account_ID_Number { get; set; }
        public Nullable<System.DateTime> Time_Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_order> Customer_order { get; set; }
        public virtual Customer_Account Customer_Account { get; set; }
    }
}
