//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIT14_ASSIGNMENT_PIZZA_ORDERING_SYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_order()
        {
            this.Order_Side = new HashSet<Order_Side>();
            this.Order_Topping = new HashSet<Order_Topping>();
        }
    
        public int Order_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string Preset_menu_item { get; set; }
        public string Pizza_size { get; set; }
        public string Crust_size { get; set; }
        public string Cheese_type { get; set; }
        public string Dough_type { get; set; }
        public string Sides_added_ { get; set; }
        public string Toppings_added_ { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Side> Order_Side { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Topping> Order_Topping { get; set; }
    }
}
