//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIT14_ASSIGNMENT_PIZZA_ORDERING_SYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Side
    {
        public int Order_ID { get; set; }
        public int Sides_ID { get; set; }
    
        public virtual Customer_order Customer_order { get; set; }
        public virtual Side Side { get; set; }
    }
}
