//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIT14_ASSIGNMENT_PIZZA_ORDERING_SYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Session_ID { get; set; }
        public Nullable<int> Account_ID_Number { get; set; }
        public Nullable<System.DateTime> TimeOfLogin { get; set; }
        public Nullable<System.DateTime> TimeOfLogOut { get; set; }
        public string Access_Level { get; set; }
    
        public virtual Customer_Account Customer_Account { get; set; }
        public virtual Kitchen_Staff_Account Kitchen_Staff_Account { get; set; }
        public virtual Manager_Account Manager_Account { get; set; }
    }
}
