//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIT14_ASSIGNMENT_PIZZA_ORDERING_SYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topping
    {
        public int Topping_ID { get; set; }
        public string Pepperroni { get; set; }
        public string Green_Onions { get; set; }
        public string Red_Onions { get; set; }
        public string Ancovies { get; set; }
        public string Mushrooms { get; set; }
        public string Black_olives { get; set; }
        public string Ham { get; set; }
        public string Pineapple { get; set; }
    
        public virtual Order_Topping Order_Topping { get; set; }
    }
}
